site_name: 乐享笔记
site_description: '总结，重用，知识结构梳理'
repo_url: http://github.com/jesshaw/mynotes
repo_name: mynotes
edit_uri: edit/main/

# Copyright
copyright: Copyright &copy; 2006 - 2024 Jes Shaw

theme:
  language: 'zh'
  favicon: assets/logo-32x32-white.png
  logo: assets/logo-180x180-white.png
  name: material
  custom_dir: custome_theme/
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    # - toc.integrate # Navigation integration
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - green: "(prefers-color-scheme: light)"
      scheme: lexiangmiao
      toggle:
        icon: material/weather-night
        name: 深色
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 浅色


# extra_css:
#   - stylesheets/extra.css

extra:
  generator: false
  # alternate:
  #   - name: English
  #     link: ./en/
  #     lang: en
  #   - name: 中文
  #     link: ./zh/
  #     lang: zh
  # search:
  #   language: 'jp'
  version:
    provider: mike

markdown_extensions:
  - plantuml_markdown:
      format: svg
  # 打包是在容器内访问plantuml，侧需要查看plantuml服务的docker0地址，如172.21.0.1，通常是网关
  # 若是通过主机访问则通过localhost直接访问就可以。当然也可以直接指定官网，但速度慢
      # server:  http://192.168.232.81:8075
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:  # 表情和品牌图标支持
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list # markdown按钮样式支持, 通地属性
  - md_in_html
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  # - meta
  - abbr
  - pymdownx.snippets:
      base_path: docs/includes
      check_paths: true
  - admonition

plugins:
  # 通过.pages文件来定义导航 https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages:
      strict: false
  - search  
  - codeinclude:
      title_mode: pymdownx.tabbed  
  - glightbox