name: Gh-pages Deploy
run-name: ${{ github.actor }} is deploying to github 🚀
on:
  push:    
    branches:
      - 'main'
env:
  GIT_COMMITTER_NAME: jesshaw
  GIT_COMMITTER_EMAIL: jesshaw@126.com
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jesshaw/mynotes:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}    
      # volumes:
      #   - ${{ github.workspace }}:/docs
    #   env:
    #     NODE_ENV: development
    #   ports:
    #     - 80
    #   options: --cpus 1
    steps:  
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print Current Directory
        run: pwd            
      - name: List Files
        run: ls -al      
      - name: permission
        run: git config --global --add safe.directory /__w/mynotes/mynotes
      - name: Deploy documentation
        run: git pull origin gh-pages && mike deploy --update-aliases --push  v0.9.2 latest
        # run: mkdocs gh-deploy --force
      - name: Show version list
        run: mike list
